# Generated by Django 5.1.7 on 2025-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('admin', 'Admin')], max_length=20, verbose_name='Role'),
        ),
    ]
