# Generated by Django 5.1.7 on 2025-04-21 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='international_barcode',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='International Barcode'),
        ),
    ]
