# Generated by Django 5.1.7 on 2025-04-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_manufacturer_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='g', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='last_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.supplier'),
        ),
    ]
