# Generated by Django 5.1.7 on 2025-04-08 02:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_name_alter_medicine_last_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
