# Generated by Django 5.1.7 on 2025-04-08 02:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_manufacturer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EG'),
        ),
    ]
