# Generated by Django 5.1.7 on 2025-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_supplier_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
