# Generated by Django 5.1.7 on 2025-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_integer',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
