# Generated by Django 5.1.7 on 2025-04-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_discount_orderitem_discount_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_before',
        ),
    ]
