# Generated by Django 5.1.7 on 2025-04-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_supplier_city'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='unique_medicine_per_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_integer',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='medicine.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_before_discount',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
